######################################################################
#
# File name : struct_test_compile.do
# Created on: Tue Sep 05 11:06:07 +07 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -sv -work xil_defaultlib  \
"../../../../src/struct_test.sv" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

