######################################################################
#
# File name : struct_test_simulate.do
# Created on: Tue Sep 05 11:06:07 +07 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib struct_test_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {struct_test_wave.do}

view wave
view structure
view signals

do {struct_test.udo}

run 1000ns
