######################################################################
#
# File name : struct_test_wave.do
# Created on: Tue Sep 05 10:27:33 +07 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
