######################################################################
#
# File name : struct_test_elaborate.do
# Created on: Tue Sep 05 11:06:07 +07 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.struct_test xil_defaultlib.glbl -o struct_test_opt
